name: Keploy API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  keploy-tests:
    runs-on: ubuntu-latest

    

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "@dbPOST91"
          POSTGRES_DB: 	plantoplan
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Start the API server
        run: npm start &
      
      - name: Wait for API to be ready
        run: sleep 10

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite --app=791b276a-6bb3-4b50-aa4d-11bb0e58d376 --base-path http://localhost:8080 --cloud
